#created on: Aug 31, 2009
package edu.ucsc.eis.mario

#list any import classes here.
import edu.ucsc.eis.mario.sprites.Mario


#declare any global variables here

rule "Output if Mario is ducking"
	when
		$mario : Mario()
		eval($mario.isDucking())
	then 
		System.err.println("Mario is ducking!");
end

rule "Stop Mario interaction if he is dead"
    when
        $mario : Mario(deathTime > 0)
    then
        System.err.println("Mario is dead");
end
